/** Shared defaults for new users (auth register + admin create user). */
export function defaultPreferences() {
  return {
    themeId: 'cozy',
    primaryColor: '#e07a5f',
    avatarColor: '#81b29a',
    accentColor: '#f2cc8f',
    avatarId: 'smile',
    buddyId: 'luna',
    motivationalMessages: ['You’ve got this.', 'Small steps count.', 'Breathe and begin.'],
    animationsEnabled: true,
    vibrationEnabled: true,
    fontSize: 'md',
    dailyGoalMinutes: 60,
    language: 'en',
    timezone: 'UTC',
    defaultFocusMinutes: 25,
    ttsEnabled: true,
    ambientDefault: 'off',
    compactMode: false,
    showFocusTips: true,
    weekStartsOn: 1,
    highContrast: false,
    ttsAlertMinutes: [10, 5, 1],
    ttsRate: 1,
    ttsPitch: 1,
    interfaceAccent: 'custom',
    fontFamily: 'nunito',
    focusVoiceCuesEnabled: true,
    uiColorPreset: 'default',
    boltBodyColor: '#81b29a',
    boltAccessoryHat: false,
    boltAccessoryGlasses: false,
    sessionCompleteSound: 'lofi',
  };
}
